name: Publish package

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v3

      # Node.js 설정
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # npm 인증 설정
      - name: Setup npm auth
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # 의존성 설치
      - run: npm install

      # 빌드 실행
      - run: npm run build

      # Git 사용자 정보 설정 (버전 업데이트와 푸시를 위해)
      - name: Set git config
        run: |
          git config --global user.email "bstnqls96@gamil.com"
          git config --global user.name "sssssubin"

      # 변경 사항을 자동으로 커밋 (없으면 건너뜀)
      - name: Commit changes if any
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto commit before version update"

      # 버전 업데이트
      - name: Version bump
        run: |
          npm version patch -m "Upgrade to version %s"

      # GitHub Actions 토큰을 사용한 git push
      - name: Push changes to GitHub
        run: |
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/sssssubin/common-front.git HEAD:main
          git push --tags

      # 패키지 배포
      - run: npm publish --registry=https://npm.pkg.github.com
