name: Publish package

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v3

      # Node.js 18 설정
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # npm 인증 설정
      - name: Setup npm auth
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # 의존성 설치
      - run: npm install

      # Git 사용자 설정
      - name: Set git user
        run: |
          git config --global user.email "bstnqls96@gamil.com"
          git config --global user.name "sssssubin"

      # 빌드 실행
      - run: npm run build

      # 변경 사항 체크 후 커밋
      - name: Auto commit before version update
        run: |
          git status
          git add .
          if git diff --cached --quiet; then
            echo "커밋할 변경 사항이 없습니다"
          else
            git commit -m "버전 업데이트 전에 자동 커밋"
          fi

      # 패키지 배포
      - run: npm version patch && npm publish --registry=https://npm.pkg.github.com
